// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/simple_proto.proto

// Protobuf Java Version: 3.25.0
package org.cs511.proto;

public final class SimpleProto {
  private SimpleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface full_descOrBuilder extends
      // @@protoc_insertion_point(interface_extends:full_desc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sort = 1;</code>
     * @return The sort.
     */
    java.lang.String getSort();
    /**
     * <code>string sort = 1;</code>
     * @return The bytes for sort.
     */
    com.google.protobuf.ByteString
        getSortBytes();

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code full_desc}
   */
  public static final class full_desc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:full_desc)
      full_descOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use full_desc.newBuilder() to construct.
    private full_desc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private full_desc() {
      sort_ = "";
      desc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new full_desc();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cs511.proto.SimpleProto.internal_static_full_desc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cs511.proto.SimpleProto.internal_static_full_desc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cs511.proto.SimpleProto.full_desc.class, org.cs511.proto.SimpleProto.full_desc.Builder.class);
    }

    public static final int SORT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sort_ = "";
    /**
     * <code>string sort = 1;</code>
     * @return The sort.
     */
    @java.lang.Override
    public java.lang.String getSort() {
      java.lang.Object ref = sort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sort_ = s;
        return s;
      }
    }
    /**
     * <code>string sort = 1;</code>
     * @return The bytes for sort.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSortBytes() {
      java.lang.Object ref = sort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sort_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sort_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cs511.proto.SimpleProto.full_desc)) {
        return super.equals(obj);
      }
      org.cs511.proto.SimpleProto.full_desc other = (org.cs511.proto.SimpleProto.full_desc) obj;

      if (!getSort()
          .equals(other.getSort())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + getSort().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.cs511.proto.SimpleProto.full_desc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.cs511.proto.SimpleProto.full_desc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.SimpleProto.full_desc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cs511.proto.SimpleProto.full_desc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code full_desc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:full_desc)
        org.cs511.proto.SimpleProto.full_descOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cs511.proto.SimpleProto.internal_static_full_desc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cs511.proto.SimpleProto.internal_static_full_desc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cs511.proto.SimpleProto.full_desc.class, org.cs511.proto.SimpleProto.full_desc.Builder.class);
      }

      // Construct using org.cs511.proto.SimpleProto.full_desc.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sort_ = "";
        desc_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cs511.proto.SimpleProto.internal_static_full_desc_descriptor;
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.full_desc getDefaultInstanceForType() {
        return org.cs511.proto.SimpleProto.full_desc.getDefaultInstance();
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.full_desc build() {
        org.cs511.proto.SimpleProto.full_desc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.full_desc buildPartial() {
        org.cs511.proto.SimpleProto.full_desc result = new org.cs511.proto.SimpleProto.full_desc(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.cs511.proto.SimpleProto.full_desc result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sort_ = sort_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.desc_ = desc_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cs511.proto.SimpleProto.full_desc) {
          return mergeFrom((org.cs511.proto.SimpleProto.full_desc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cs511.proto.SimpleProto.full_desc other) {
        if (other == org.cs511.proto.SimpleProto.full_desc.getDefaultInstance()) return this;
        if (!other.getSort().isEmpty()) {
          sort_ = other.sort_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sort_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                desc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sort_ = "";
      /**
       * <code>string sort = 1;</code>
       * @return The sort.
       */
      public java.lang.String getSort() {
        java.lang.Object ref = sort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sort_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sort = 1;</code>
       * @return The bytes for sort.
       */
      public com.google.protobuf.ByteString
          getSortBytes() {
        java.lang.Object ref = sort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sort = 1;</code>
       * @param value The sort to set.
       * @return This builder for chaining.
       */
      public Builder setSort(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sort_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string sort = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSort() {
        sort_ = getDefaultInstance().getSort();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string sort = 1;</code>
       * @param value The bytes for sort to set.
       * @return This builder for chaining.
       */
      public Builder setSortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sort_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       * @return The desc.
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        desc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        desc_ = getDefaultInstance().getDesc();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        desc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:full_desc)
    }

    // @@protoc_insertion_point(class_scope:full_desc)
    private static final org.cs511.proto.SimpleProto.full_desc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cs511.proto.SimpleProto.full_desc();
    }

    public static org.cs511.proto.SimpleProto.full_desc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<full_desc>
        PARSER = new com.google.protobuf.AbstractParser<full_desc>() {
      @java.lang.Override
      public full_desc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<full_desc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<full_desc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cs511.proto.SimpleProto.full_desc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface simple_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simple_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string developer = 2;</code>
     * @return The developer.
     */
    java.lang.String getDeveloper();
    /**
     * <code>string developer = 2;</code>
     * @return The bytes for developer.
     */
    com.google.protobuf.ByteString
        getDeveloperBytes();

    /**
     * <code>string publisher = 3;</code>
     * @return The publisher.
     */
    java.lang.String getPublisher();
    /**
     * <code>string publisher = 3;</code>
     * @return The bytes for publisher.
     */
    com.google.protobuf.ByteString
        getPublisherBytes();

    /**
     * <code>.full_desc d = 4;</code>
     * @return Whether the d field is set.
     */
    boolean hasD();
    /**
     * <code>.full_desc d = 4;</code>
     * @return The d.
     */
    org.cs511.proto.SimpleProto.full_desc getD();
    /**
     * <code>.full_desc d = 4;</code>
     */
    org.cs511.proto.SimpleProto.full_descOrBuilder getDOrBuilder();
  }
  /**
   * Protobuf type {@code simple_proto}
   */
  public static final class simple_proto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simple_proto)
      simple_protoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use simple_proto.newBuilder() to construct.
    private simple_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private simple_proto() {
      date_ = "";
      developer_ = "";
      publisher_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new simple_proto();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cs511.proto.SimpleProto.internal_static_simple_proto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cs511.proto.SimpleProto.internal_static_simple_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cs511.proto.SimpleProto.simple_proto.class, org.cs511.proto.SimpleProto.simple_proto.Builder.class);
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVELOPER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object developer_ = "";
    /**
     * <code>string developer = 2;</code>
     * @return The developer.
     */
    @java.lang.Override
    public java.lang.String getDeveloper() {
      java.lang.Object ref = developer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        developer_ = s;
        return s;
      }
    }
    /**
     * <code>string developer = 2;</code>
     * @return The bytes for developer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeveloperBytes() {
      java.lang.Object ref = developer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        developer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object publisher_ = "";
    /**
     * <code>string publisher = 3;</code>
     * @return The publisher.
     */
    @java.lang.Override
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <code>string publisher = 3;</code>
     * @return The bytes for publisher.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int D_FIELD_NUMBER = 4;
    private org.cs511.proto.SimpleProto.full_desc d_;
    /**
     * <code>.full_desc d = 4;</code>
     * @return Whether the d field is set.
     */
    @java.lang.Override
    public boolean hasD() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.full_desc d = 4;</code>
     * @return The d.
     */
    @java.lang.Override
    public org.cs511.proto.SimpleProto.full_desc getD() {
      return d_ == null ? org.cs511.proto.SimpleProto.full_desc.getDefaultInstance() : d_;
    }
    /**
     * <code>.full_desc d = 4;</code>
     */
    @java.lang.Override
    public org.cs511.proto.SimpleProto.full_descOrBuilder getDOrBuilder() {
      return d_ == null ? org.cs511.proto.SimpleProto.full_desc.getDefaultInstance() : d_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(developer_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, developer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publisher_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, publisher_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getD());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(developer_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, developer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publisher_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, publisher_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getD());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cs511.proto.SimpleProto.simple_proto)) {
        return super.equals(obj);
      }
      org.cs511.proto.SimpleProto.simple_proto other = (org.cs511.proto.SimpleProto.simple_proto) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getDeveloper()
          .equals(other.getDeveloper())) return false;
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
      if (hasD() != other.hasD()) return false;
      if (hasD()) {
        if (!getD()
            .equals(other.getD())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + DEVELOPER_FIELD_NUMBER;
      hash = (53 * hash) + getDeveloper().hashCode();
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      if (hasD()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + getD().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.cs511.proto.SimpleProto.simple_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.cs511.proto.SimpleProto.simple_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.SimpleProto.simple_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cs511.proto.SimpleProto.simple_proto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simple_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simple_proto)
        org.cs511.proto.SimpleProto.simple_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cs511.proto.SimpleProto.internal_static_simple_proto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cs511.proto.SimpleProto.internal_static_simple_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cs511.proto.SimpleProto.simple_proto.class, org.cs511.proto.SimpleProto.simple_proto.Builder.class);
      }

      // Construct using org.cs511.proto.SimpleProto.simple_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        date_ = "";
        developer_ = "";
        publisher_ = "";
        d_ = null;
        if (dBuilder_ != null) {
          dBuilder_.dispose();
          dBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cs511.proto.SimpleProto.internal_static_simple_proto_descriptor;
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.simple_proto getDefaultInstanceForType() {
        return org.cs511.proto.SimpleProto.simple_proto.getDefaultInstance();
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.simple_proto build() {
        org.cs511.proto.SimpleProto.simple_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cs511.proto.SimpleProto.simple_proto buildPartial() {
        org.cs511.proto.SimpleProto.simple_proto result = new org.cs511.proto.SimpleProto.simple_proto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.cs511.proto.SimpleProto.simple_proto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.date_ = date_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.developer_ = developer_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.publisher_ = publisher_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.d_ = dBuilder_ == null
              ? d_
              : dBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cs511.proto.SimpleProto.simple_proto) {
          return mergeFrom((org.cs511.proto.SimpleProto.simple_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cs511.proto.SimpleProto.simple_proto other) {
        if (other == org.cs511.proto.SimpleProto.simple_proto.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDeveloper().isEmpty()) {
          developer_ = other.developer_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasD()) {
          mergeD(other.getD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                developer_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                publisher_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getDFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object developer_ = "";
      /**
       * <code>string developer = 2;</code>
       * @return The developer.
       */
      public java.lang.String getDeveloper() {
        java.lang.Object ref = developer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          developer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string developer = 2;</code>
       * @return The bytes for developer.
       */
      public com.google.protobuf.ByteString
          getDeveloperBytes() {
        java.lang.Object ref = developer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          developer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string developer = 2;</code>
       * @param value The developer to set.
       * @return This builder for chaining.
       */
      public Builder setDeveloper(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        developer_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string developer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeveloper() {
        developer_ = getDefaultInstance().getDeveloper();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string developer = 2;</code>
       * @param value The bytes for developer to set.
       * @return This builder for chaining.
       */
      public Builder setDeveloperBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        developer_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <code>string publisher = 3;</code>
       * @return The publisher.
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string publisher = 3;</code>
       * @return The bytes for publisher.
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publisher = 3;</code>
       * @param value The publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        publisher_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisher() {
        publisher_ = getDefaultInstance().getPublisher();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 3;</code>
       * @param value The bytes for publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        publisher_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private org.cs511.proto.SimpleProto.full_desc d_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.cs511.proto.SimpleProto.full_desc, org.cs511.proto.SimpleProto.full_desc.Builder, org.cs511.proto.SimpleProto.full_descOrBuilder> dBuilder_;
      /**
       * <code>.full_desc d = 4;</code>
       * @return Whether the d field is set.
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.full_desc d = 4;</code>
       * @return The d.
       */
      public org.cs511.proto.SimpleProto.full_desc getD() {
        if (dBuilder_ == null) {
          return d_ == null ? org.cs511.proto.SimpleProto.full_desc.getDefaultInstance() : d_;
        } else {
          return dBuilder_.getMessage();
        }
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public Builder setD(org.cs511.proto.SimpleProto.full_desc value) {
        if (dBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          d_ = value;
        } else {
          dBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public Builder setD(
          org.cs511.proto.SimpleProto.full_desc.Builder builderForValue) {
        if (dBuilder_ == null) {
          d_ = builderForValue.build();
        } else {
          dBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public Builder mergeD(org.cs511.proto.SimpleProto.full_desc value) {
        if (dBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            d_ != null &&
            d_ != org.cs511.proto.SimpleProto.full_desc.getDefaultInstance()) {
            getDBuilder().mergeFrom(value);
          } else {
            d_ = value;
          }
        } else {
          dBuilder_.mergeFrom(value);
        }
        if (d_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000008);
        d_ = null;
        if (dBuilder_ != null) {
          dBuilder_.dispose();
          dBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public org.cs511.proto.SimpleProto.full_desc.Builder getDBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDFieldBuilder().getBuilder();
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      public org.cs511.proto.SimpleProto.full_descOrBuilder getDOrBuilder() {
        if (dBuilder_ != null) {
          return dBuilder_.getMessageOrBuilder();
        } else {
          return d_ == null ?
              org.cs511.proto.SimpleProto.full_desc.getDefaultInstance() : d_;
        }
      }
      /**
       * <code>.full_desc d = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.cs511.proto.SimpleProto.full_desc, org.cs511.proto.SimpleProto.full_desc.Builder, org.cs511.proto.SimpleProto.full_descOrBuilder> 
          getDFieldBuilder() {
        if (dBuilder_ == null) {
          dBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.cs511.proto.SimpleProto.full_desc, org.cs511.proto.SimpleProto.full_desc.Builder, org.cs511.proto.SimpleProto.full_descOrBuilder>(
                  getD(),
                  getParentForChildren(),
                  isClean());
          d_ = null;
        }
        return dBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simple_proto)
    }

    // @@protoc_insertion_point(class_scope:simple_proto)
    private static final org.cs511.proto.SimpleProto.simple_proto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cs511.proto.SimpleProto.simple_proto();
    }

    public static org.cs511.proto.SimpleProto.simple_proto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<simple_proto>
        PARSER = new com.google.protobuf.AbstractParser<simple_proto>() {
      @java.lang.Override
      public simple_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<simple_proto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<simple_proto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cs511.proto.SimpleProto.simple_proto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_full_desc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_full_desc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simple_proto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simple_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/proto/simple_proto.proto\"\'\n\tf" +
      "ull_desc\022\014\n\004sort\030\001 \001(\t\022\014\n\004desc\030\002 \001(\t\"Y\n\014" +
      "simple_proto\022\014\n\004date\030\001 \001(\t\022\021\n\tdeveloper\030" +
      "\002 \001(\t\022\021\n\tpublisher\030\003 \001(\t\022\025\n\001d\030\004 \001(\0132\n.fu" +
      "ll_descB\021\n\017org.cs511.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_full_desc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_full_desc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_full_desc_descriptor,
        new java.lang.String[] { "Sort", "Desc", });
    internal_static_simple_proto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_simple_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simple_proto_descriptor,
        new java.lang.String[] { "Date", "Developer", "Publisher", "D", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
