/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cs511.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DummyAvroHighRequirementsMinimum extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3113127111827749517L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DummyAvroHighRequirementsMinimum\",\"namespace\":\"org.cs511.avro\",\"fields\":[{\"name\":\"windows\",\"type\":{\"type\":\"record\",\"name\":\"DummyAvroHighRequirementsMinimumWindows\",\"fields\":[{\"name\":\"processor\",\"type\":\"string\"},{\"name\":\"memory\",\"type\":\"string\"},{\"name\":\"graphics\",\"type\":\"string\"},{\"name\":\"os\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DummyAvroHighRequirementsMinimum> ENCODER =
      new BinaryMessageEncoder<DummyAvroHighRequirementsMinimum>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DummyAvroHighRequirementsMinimum> DECODER =
      new BinaryMessageDecoder<DummyAvroHighRequirementsMinimum>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DummyAvroHighRequirementsMinimum> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirementsMinimum> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirementsMinimum> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DummyAvroHighRequirementsMinimum>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DummyAvroHighRequirementsMinimum to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DummyAvroHighRequirementsMinimum from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DummyAvroHighRequirementsMinimum instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DummyAvroHighRequirementsMinimum fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows windows;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DummyAvroHighRequirementsMinimum() {}

  /**
   * All-args constructor.
   * @param windows The new value for windows
   */
  public DummyAvroHighRequirementsMinimum(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows windows) {
    this.windows = windows;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return windows;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: windows = (org.cs511.avro.DummyAvroHighRequirementsMinimumWindows)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'windows' field.
   * @return The value of the 'windows' field.
   */
  public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows getWindows() {
    return windows;
  }


  /**
   * Sets the value of the 'windows' field.
   * @param value the value to set.
   */
  public void setWindows(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows value) {
    this.windows = value;
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimum RecordBuilder.
   * @return A new DummyAvroHighRequirementsMinimum RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder newBuilder() {
    return new org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder();
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimum RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DummyAvroHighRequirementsMinimum RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder(other);
    }
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimum RecordBuilder by copying an existing DummyAvroHighRequirementsMinimum instance.
   * @param other The existing instance to copy.
   * @return A new DummyAvroHighRequirementsMinimum RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimum other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder(other);
    }
  }

  /**
   * RecordBuilder for DummyAvroHighRequirementsMinimum instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DummyAvroHighRequirementsMinimum>
    implements org.apache.avro.data.RecordBuilder<DummyAvroHighRequirementsMinimum> {

    private org.cs511.avro.DummyAvroHighRequirementsMinimumWindows windows;
    private org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder windowsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.windows)) {
        this.windows = data().deepCopy(fields()[0].schema(), other.windows);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasWindowsBuilder()) {
        this.windowsBuilder = org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.newBuilder(other.getWindowsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DummyAvroHighRequirementsMinimum instance
     * @param other The existing instance to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirementsMinimum other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.windows)) {
        this.windows = data().deepCopy(fields()[0].schema(), other.windows);
        fieldSetFlags()[0] = true;
      }
      this.windowsBuilder = null;
    }

    /**
      * Gets the value of the 'windows' field.
      * @return The value.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows getWindows() {
      return windows;
    }


    /**
      * Sets the value of the 'windows' field.
      * @param value The value of 'windows'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder setWindows(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows value) {
      validate(fields()[0], value);
      this.windowsBuilder = null;
      this.windows = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'windows' field has been set.
      * @return True if the 'windows' field has been set, false otherwise.
      */
    public boolean hasWindows() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'windows' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder getWindowsBuilder() {
      if (windowsBuilder == null) {
        if (hasWindows()) {
          setWindowsBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.newBuilder(windows));
        } else {
          setWindowsBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.newBuilder());
        }
      }
      return windowsBuilder;
    }

    /**
     * Sets the Builder instance for the 'windows' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder setWindowsBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder value) {
      clearWindows();
      windowsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'windows' field has an active Builder instance
     * @return True if the 'windows' field has an active Builder instance
     */
    public boolean hasWindowsBuilder() {
      return windowsBuilder != null;
    }

    /**
      * Clears the value of the 'windows' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder clearWindows() {
      windows = null;
      windowsBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DummyAvroHighRequirementsMinimum build() {
      try {
        DummyAvroHighRequirementsMinimum record = new DummyAvroHighRequirementsMinimum();
        if (windowsBuilder != null) {
          try {
            record.windows = this.windowsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("windows"));
            throw e;
          }
        } else {
          record.windows = fieldSetFlags()[0] ? this.windows : (org.cs511.avro.DummyAvroHighRequirementsMinimumWindows) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DummyAvroHighRequirementsMinimum>
    WRITER$ = (org.apache.avro.io.DatumWriter<DummyAvroHighRequirementsMinimum>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DummyAvroHighRequirementsMinimum>
    READER$ = (org.apache.avro.io.DatumReader<DummyAvroHighRequirementsMinimum>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.windows.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.windows == null) {
        this.windows = new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows();
      }
      this.windows.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.windows == null) {
            this.windows = new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows();
          }
          this.windows.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










