/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cs511.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DummyAvroHighRequirementsMinimumWindows extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1805445869761522433L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DummyAvroHighRequirementsMinimumWindows\",\"namespace\":\"org.cs511.avro\",\"fields\":[{\"name\":\"processor\",\"type\":\"string\"},{\"name\":\"memory\",\"type\":\"string\"},{\"name\":\"graphics\",\"type\":\"string\"},{\"name\":\"os\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DummyAvroHighRequirementsMinimumWindows> ENCODER =
      new BinaryMessageEncoder<DummyAvroHighRequirementsMinimumWindows>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DummyAvroHighRequirementsMinimumWindows> DECODER =
      new BinaryMessageDecoder<DummyAvroHighRequirementsMinimumWindows>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DummyAvroHighRequirementsMinimumWindows> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirementsMinimumWindows> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirementsMinimumWindows> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DummyAvroHighRequirementsMinimumWindows>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DummyAvroHighRequirementsMinimumWindows to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DummyAvroHighRequirementsMinimumWindows from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DummyAvroHighRequirementsMinimumWindows instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DummyAvroHighRequirementsMinimumWindows fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence processor;
  @Deprecated public java.lang.CharSequence memory;
  @Deprecated public java.lang.CharSequence graphics;
  @Deprecated public java.lang.CharSequence os;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DummyAvroHighRequirementsMinimumWindows() {}

  /**
   * All-args constructor.
   * @param processor The new value for processor
   * @param memory The new value for memory
   * @param graphics The new value for graphics
   * @param os The new value for os
   */
  public DummyAvroHighRequirementsMinimumWindows(java.lang.CharSequence processor, java.lang.CharSequence memory, java.lang.CharSequence graphics, java.lang.CharSequence os) {
    this.processor = processor;
    this.memory = memory;
    this.graphics = graphics;
    this.os = os;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return processor;
    case 1: return memory;
    case 2: return graphics;
    case 3: return os;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: processor = (java.lang.CharSequence)value$; break;
    case 1: memory = (java.lang.CharSequence)value$; break;
    case 2: graphics = (java.lang.CharSequence)value$; break;
    case 3: os = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'processor' field.
   * @return The value of the 'processor' field.
   */
  public java.lang.CharSequence getProcessor() {
    return processor;
  }


  /**
   * Sets the value of the 'processor' field.
   * @param value the value to set.
   */
  public void setProcessor(java.lang.CharSequence value) {
    this.processor = value;
  }

  /**
   * Gets the value of the 'memory' field.
   * @return The value of the 'memory' field.
   */
  public java.lang.CharSequence getMemory() {
    return memory;
  }


  /**
   * Sets the value of the 'memory' field.
   * @param value the value to set.
   */
  public void setMemory(java.lang.CharSequence value) {
    this.memory = value;
  }

  /**
   * Gets the value of the 'graphics' field.
   * @return The value of the 'graphics' field.
   */
  public java.lang.CharSequence getGraphics() {
    return graphics;
  }


  /**
   * Sets the value of the 'graphics' field.
   * @param value the value to set.
   */
  public void setGraphics(java.lang.CharSequence value) {
    this.graphics = value;
  }

  /**
   * Gets the value of the 'os' field.
   * @return The value of the 'os' field.
   */
  public java.lang.CharSequence getOs() {
    return os;
  }


  /**
   * Sets the value of the 'os' field.
   * @param value the value to set.
   */
  public void setOs(java.lang.CharSequence value) {
    this.os = value;
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimumWindows RecordBuilder.
   * @return A new DummyAvroHighRequirementsMinimumWindows RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder newBuilder() {
    return new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder();
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimumWindows RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DummyAvroHighRequirementsMinimumWindows RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder(other);
    }
  }

  /**
   * Creates a new DummyAvroHighRequirementsMinimumWindows RecordBuilder by copying an existing DummyAvroHighRequirementsMinimumWindows instance.
   * @param other The existing instance to copy.
   * @return A new DummyAvroHighRequirementsMinimumWindows RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder(other);
    }
  }

  /**
   * RecordBuilder for DummyAvroHighRequirementsMinimumWindows instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DummyAvroHighRequirementsMinimumWindows>
    implements org.apache.avro.data.RecordBuilder<DummyAvroHighRequirementsMinimumWindows> {

    private java.lang.CharSequence processor;
    private java.lang.CharSequence memory;
    private java.lang.CharSequence graphics;
    private java.lang.CharSequence os;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.processor)) {
        this.processor = data().deepCopy(fields()[0].schema(), other.processor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.memory)) {
        this.memory = data().deepCopy(fields()[1].schema(), other.memory);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.graphics)) {
        this.graphics = data().deepCopy(fields()[2].schema(), other.graphics);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.os)) {
        this.os = data().deepCopy(fields()[3].schema(), other.os);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DummyAvroHighRequirementsMinimumWindows instance
     * @param other The existing instance to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirementsMinimumWindows other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.processor)) {
        this.processor = data().deepCopy(fields()[0].schema(), other.processor);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.memory)) {
        this.memory = data().deepCopy(fields()[1].schema(), other.memory);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.graphics)) {
        this.graphics = data().deepCopy(fields()[2].schema(), other.graphics);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.os)) {
        this.os = data().deepCopy(fields()[3].schema(), other.os);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'processor' field.
      * @return The value.
      */
    public java.lang.CharSequence getProcessor() {
      return processor;
    }


    /**
      * Sets the value of the 'processor' field.
      * @param value The value of 'processor'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder setProcessor(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.processor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'processor' field has been set.
      * @return True if the 'processor' field has been set, false otherwise.
      */
    public boolean hasProcessor() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'processor' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder clearProcessor() {
      processor = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'memory' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemory() {
      return memory;
    }


    /**
      * Sets the value of the 'memory' field.
      * @param value The value of 'memory'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder setMemory(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.memory = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'memory' field has been set.
      * @return True if the 'memory' field has been set, false otherwise.
      */
    public boolean hasMemory() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'memory' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder clearMemory() {
      memory = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'graphics' field.
      * @return The value.
      */
    public java.lang.CharSequence getGraphics() {
      return graphics;
    }


    /**
      * Sets the value of the 'graphics' field.
      * @param value The value of 'graphics'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder setGraphics(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.graphics = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'graphics' field has been set.
      * @return True if the 'graphics' field has been set, false otherwise.
      */
    public boolean hasGraphics() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'graphics' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder clearGraphics() {
      graphics = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'os' field.
      * @return The value.
      */
    public java.lang.CharSequence getOs() {
      return os;
    }


    /**
      * Sets the value of the 'os' field.
      * @param value The value of 'os'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder setOs(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.os = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'os' field has been set.
      * @return True if the 'os' field has been set, false otherwise.
      */
    public boolean hasOs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'os' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimumWindows.Builder clearOs() {
      os = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DummyAvroHighRequirementsMinimumWindows build() {
      try {
        DummyAvroHighRequirementsMinimumWindows record = new DummyAvroHighRequirementsMinimumWindows();
        record.processor = fieldSetFlags()[0] ? this.processor : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.memory = fieldSetFlags()[1] ? this.memory : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.graphics = fieldSetFlags()[2] ? this.graphics : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.os = fieldSetFlags()[3] ? this.os : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DummyAvroHighRequirementsMinimumWindows>
    WRITER$ = (org.apache.avro.io.DatumWriter<DummyAvroHighRequirementsMinimumWindows>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DummyAvroHighRequirementsMinimumWindows>
    READER$ = (org.apache.avro.io.DatumReader<DummyAvroHighRequirementsMinimumWindows>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.processor);

    out.writeString(this.memory);

    out.writeString(this.graphics);

    out.writeString(this.os);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.processor = in.readString(this.processor instanceof Utf8 ? (Utf8)this.processor : null);

      this.memory = in.readString(this.memory instanceof Utf8 ? (Utf8)this.memory : null);

      this.graphics = in.readString(this.graphics instanceof Utf8 ? (Utf8)this.graphics : null);

      this.os = in.readString(this.os instanceof Utf8 ? (Utf8)this.os : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.processor = in.readString(this.processor instanceof Utf8 ? (Utf8)this.processor : null);
          break;

        case 1:
          this.memory = in.readString(this.memory instanceof Utf8 ? (Utf8)this.memory : null);
          break;

        case 2:
          this.graphics = in.readString(this.graphics instanceof Utf8 ? (Utf8)this.graphics : null);
          break;

        case 3:
          this.os = in.readString(this.os instanceof Utf8 ? (Utf8)this.os : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










