/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cs511.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DummyAvroHighRequirements extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5310960984616531874L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DummyAvroHighRequirements\",\"namespace\":\"org.cs511.avro\",\"fields\":[{\"name\":\"minimum\",\"type\":{\"type\":\"record\",\"name\":\"DummyAvroHighRequirementsMinimum\",\"fields\":[{\"name\":\"windows\",\"type\":{\"type\":\"record\",\"name\":\"DummyAvroHighRequirementsMinimumWindows\",\"fields\":[{\"name\":\"processor\",\"type\":\"string\"},{\"name\":\"memory\",\"type\":\"string\"},{\"name\":\"graphics\",\"type\":\"string\"},{\"name\":\"os\",\"type\":\"string\"}]}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DummyAvroHighRequirements> ENCODER =
      new BinaryMessageEncoder<DummyAvroHighRequirements>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DummyAvroHighRequirements> DECODER =
      new BinaryMessageDecoder<DummyAvroHighRequirements>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DummyAvroHighRequirements> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirements> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DummyAvroHighRequirements> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DummyAvroHighRequirements>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DummyAvroHighRequirements to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DummyAvroHighRequirements from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DummyAvroHighRequirements instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DummyAvroHighRequirements fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public org.cs511.avro.DummyAvroHighRequirementsMinimum minimum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DummyAvroHighRequirements() {}

  /**
   * All-args constructor.
   * @param minimum The new value for minimum
   */
  public DummyAvroHighRequirements(org.cs511.avro.DummyAvroHighRequirementsMinimum minimum) {
    this.minimum = minimum;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return minimum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: minimum = (org.cs511.avro.DummyAvroHighRequirementsMinimum)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'minimum' field.
   * @return The value of the 'minimum' field.
   */
  public org.cs511.avro.DummyAvroHighRequirementsMinimum getMinimum() {
    return minimum;
  }


  /**
   * Sets the value of the 'minimum' field.
   * @param value the value to set.
   */
  public void setMinimum(org.cs511.avro.DummyAvroHighRequirementsMinimum value) {
    this.minimum = value;
  }

  /**
   * Creates a new DummyAvroHighRequirements RecordBuilder.
   * @return A new DummyAvroHighRequirements RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirements.Builder newBuilder() {
    return new org.cs511.avro.DummyAvroHighRequirements.Builder();
  }

  /**
   * Creates a new DummyAvroHighRequirements RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DummyAvroHighRequirements RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirements.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirements.Builder other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirements.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirements.Builder(other);
    }
  }

  /**
   * Creates a new DummyAvroHighRequirements RecordBuilder by copying an existing DummyAvroHighRequirements instance.
   * @param other The existing instance to copy.
   * @return A new DummyAvroHighRequirements RecordBuilder
   */
  public static org.cs511.avro.DummyAvroHighRequirements.Builder newBuilder(org.cs511.avro.DummyAvroHighRequirements other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvroHighRequirements.Builder();
    } else {
      return new org.cs511.avro.DummyAvroHighRequirements.Builder(other);
    }
  }

  /**
   * RecordBuilder for DummyAvroHighRequirements instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DummyAvroHighRequirements>
    implements org.apache.avro.data.RecordBuilder<DummyAvroHighRequirements> {

    private org.cs511.avro.DummyAvroHighRequirementsMinimum minimum;
    private org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder minimumBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirements.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.minimum)) {
        this.minimum = data().deepCopy(fields()[0].schema(), other.minimum);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMinimumBuilder()) {
        this.minimumBuilder = org.cs511.avro.DummyAvroHighRequirementsMinimum.newBuilder(other.getMinimumBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DummyAvroHighRequirements instance
     * @param other The existing instance to copy.
     */
    private Builder(org.cs511.avro.DummyAvroHighRequirements other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.minimum)) {
        this.minimum = data().deepCopy(fields()[0].schema(), other.minimum);
        fieldSetFlags()[0] = true;
      }
      this.minimumBuilder = null;
    }

    /**
      * Gets the value of the 'minimum' field.
      * @return The value.
      */
    public org.cs511.avro.DummyAvroHighRequirementsMinimum getMinimum() {
      return minimum;
    }


    /**
      * Sets the value of the 'minimum' field.
      * @param value The value of 'minimum'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirements.Builder setMinimum(org.cs511.avro.DummyAvroHighRequirementsMinimum value) {
      validate(fields()[0], value);
      this.minimumBuilder = null;
      this.minimum = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'minimum' field has been set.
      * @return True if the 'minimum' field has been set, false otherwise.
      */
    public boolean hasMinimum() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'minimum' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder getMinimumBuilder() {
      if (minimumBuilder == null) {
        if (hasMinimum()) {
          setMinimumBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimum.newBuilder(minimum));
        } else {
          setMinimumBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimum.newBuilder());
        }
      }
      return minimumBuilder;
    }

    /**
     * Sets the Builder instance for the 'minimum' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.cs511.avro.DummyAvroHighRequirements.Builder setMinimumBuilder(org.cs511.avro.DummyAvroHighRequirementsMinimum.Builder value) {
      clearMinimum();
      minimumBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'minimum' field has an active Builder instance
     * @return True if the 'minimum' field has an active Builder instance
     */
    public boolean hasMinimumBuilder() {
      return minimumBuilder != null;
    }

    /**
      * Clears the value of the 'minimum' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvroHighRequirements.Builder clearMinimum() {
      minimum = null;
      minimumBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DummyAvroHighRequirements build() {
      try {
        DummyAvroHighRequirements record = new DummyAvroHighRequirements();
        if (minimumBuilder != null) {
          try {
            record.minimum = this.minimumBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("minimum"));
            throw e;
          }
        } else {
          record.minimum = fieldSetFlags()[0] ? this.minimum : (org.cs511.avro.DummyAvroHighRequirementsMinimum) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DummyAvroHighRequirements>
    WRITER$ = (org.apache.avro.io.DatumWriter<DummyAvroHighRequirements>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DummyAvroHighRequirements>
    READER$ = (org.apache.avro.io.DatumReader<DummyAvroHighRequirements>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.minimum.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.minimum == null) {
        this.minimum = new org.cs511.avro.DummyAvroHighRequirementsMinimum();
      }
      this.minimum.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.minimum == null) {
            this.minimum = new org.cs511.avro.DummyAvroHighRequirementsMinimum();
          }
          this.minimum.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










