/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cs511.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DummyAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2835861839961608826L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DummyAvro\",\"namespace\":\"org.cs511.avro\",\"fields\":[{\"name\":\"tconst\",\"type\":\"string\"},{\"name\":\"averageRating\",\"type\":\"string\"},{\"name\":\"numVotes\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DummyAvro> ENCODER =
      new BinaryMessageEncoder<DummyAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DummyAvro> DECODER =
      new BinaryMessageDecoder<DummyAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DummyAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DummyAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DummyAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DummyAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DummyAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DummyAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DummyAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DummyAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence tconst;
  @Deprecated public java.lang.CharSequence averageRating;
  @Deprecated public java.lang.CharSequence numVotes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DummyAvro() {}

  /**
   * All-args constructor.
   * @param tconst The new value for tconst
   * @param averageRating The new value for averageRating
   * @param numVotes The new value for numVotes
   */
  public DummyAvro(java.lang.CharSequence tconst, java.lang.CharSequence averageRating, java.lang.CharSequence numVotes) {
    this.tconst = tconst;
    this.averageRating = averageRating;
    this.numVotes = numVotes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tconst;
    case 1: return averageRating;
    case 2: return numVotes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tconst = (java.lang.CharSequence)value$; break;
    case 1: averageRating = (java.lang.CharSequence)value$; break;
    case 2: numVotes = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tconst' field.
   * @return The value of the 'tconst' field.
   */
  public java.lang.CharSequence getTconst() {
    return tconst;
  }


  /**
   * Sets the value of the 'tconst' field.
   * @param value the value to set.
   */
  public void setTconst(java.lang.CharSequence value) {
    this.tconst = value;
  }

  /**
   * Gets the value of the 'averageRating' field.
   * @return The value of the 'averageRating' field.
   */
  public java.lang.CharSequence getAverageRating() {
    return averageRating;
  }


  /**
   * Sets the value of the 'averageRating' field.
   * @param value the value to set.
   */
  public void setAverageRating(java.lang.CharSequence value) {
    this.averageRating = value;
  }

  /**
   * Gets the value of the 'numVotes' field.
   * @return The value of the 'numVotes' field.
   */
  public java.lang.CharSequence getNumVotes() {
    return numVotes;
  }


  /**
   * Sets the value of the 'numVotes' field.
   * @param value the value to set.
   */
  public void setNumVotes(java.lang.CharSequence value) {
    this.numVotes = value;
  }

  /**
   * Creates a new DummyAvro RecordBuilder.
   * @return A new DummyAvro RecordBuilder
   */
  public static org.cs511.avro.DummyAvro.Builder newBuilder() {
    return new org.cs511.avro.DummyAvro.Builder();
  }

  /**
   * Creates a new DummyAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DummyAvro RecordBuilder
   */
  public static org.cs511.avro.DummyAvro.Builder newBuilder(org.cs511.avro.DummyAvro.Builder other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvro.Builder();
    } else {
      return new org.cs511.avro.DummyAvro.Builder(other);
    }
  }

  /**
   * Creates a new DummyAvro RecordBuilder by copying an existing DummyAvro instance.
   * @param other The existing instance to copy.
   * @return A new DummyAvro RecordBuilder
   */
  public static org.cs511.avro.DummyAvro.Builder newBuilder(org.cs511.avro.DummyAvro other) {
    if (other == null) {
      return new org.cs511.avro.DummyAvro.Builder();
    } else {
      return new org.cs511.avro.DummyAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for DummyAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DummyAvro>
    implements org.apache.avro.data.RecordBuilder<DummyAvro> {

    private java.lang.CharSequence tconst;
    private java.lang.CharSequence averageRating;
    private java.lang.CharSequence numVotes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.cs511.avro.DummyAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tconst)) {
        this.tconst = data().deepCopy(fields()[0].schema(), other.tconst);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.averageRating)) {
        this.averageRating = data().deepCopy(fields()[1].schema(), other.averageRating);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.numVotes)) {
        this.numVotes = data().deepCopy(fields()[2].schema(), other.numVotes);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DummyAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(org.cs511.avro.DummyAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tconst)) {
        this.tconst = data().deepCopy(fields()[0].schema(), other.tconst);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.averageRating)) {
        this.averageRating = data().deepCopy(fields()[1].schema(), other.averageRating);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numVotes)) {
        this.numVotes = data().deepCopy(fields()[2].schema(), other.numVotes);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'tconst' field.
      * @return The value.
      */
    public java.lang.CharSequence getTconst() {
      return tconst;
    }


    /**
      * Sets the value of the 'tconst' field.
      * @param value The value of 'tconst'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder setTconst(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tconst = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tconst' field has been set.
      * @return True if the 'tconst' field has been set, false otherwise.
      */
    public boolean hasTconst() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tconst' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder clearTconst() {
      tconst = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'averageRating' field.
      * @return The value.
      */
    public java.lang.CharSequence getAverageRating() {
      return averageRating;
    }


    /**
      * Sets the value of the 'averageRating' field.
      * @param value The value of 'averageRating'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder setAverageRating(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.averageRating = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'averageRating' field has been set.
      * @return True if the 'averageRating' field has been set, false otherwise.
      */
    public boolean hasAverageRating() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'averageRating' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder clearAverageRating() {
      averageRating = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numVotes' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumVotes() {
      return numVotes;
    }


    /**
      * Sets the value of the 'numVotes' field.
      * @param value The value of 'numVotes'.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder setNumVotes(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.numVotes = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numVotes' field has been set.
      * @return True if the 'numVotes' field has been set, false otherwise.
      */
    public boolean hasNumVotes() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numVotes' field.
      * @return This builder.
      */
    public org.cs511.avro.DummyAvro.Builder clearNumVotes() {
      numVotes = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DummyAvro build() {
      try {
        DummyAvro record = new DummyAvro();
        record.tconst = fieldSetFlags()[0] ? this.tconst : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.averageRating = fieldSetFlags()[1] ? this.averageRating : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.numVotes = fieldSetFlags()[2] ? this.numVotes : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DummyAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<DummyAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DummyAvro>
    READER$ = (org.apache.avro.io.DatumReader<DummyAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tconst);

    out.writeString(this.averageRating);

    out.writeString(this.numVotes);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tconst = in.readString(this.tconst instanceof Utf8 ? (Utf8)this.tconst : null);

      this.averageRating = in.readString(this.averageRating instanceof Utf8 ? (Utf8)this.averageRating : null);

      this.numVotes = in.readString(this.numVotes instanceof Utf8 ? (Utf8)this.numVotes : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tconst = in.readString(this.tconst instanceof Utf8 ? (Utf8)this.tconst : null);
          break;

        case 1:
          this.averageRating = in.readString(this.averageRating instanceof Utf8 ? (Utf8)this.averageRating : null);
          break;

        case 2:
          this.numVotes = in.readString(this.numVotes instanceof Utf8 ? (Utf8)this.numVotes : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










