// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dummy_proto.proto

package org.cs511.proto;

public final class DummyProto {
  private DummyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface dummy_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dummy_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 field1 = 1;</code>
     * @return The field1.
     */
    int getField1();

    /**
     * <code>string field2 = 2;</code>
     * @return The field2.
     */
    java.lang.String getField2();
    /**
     * <code>string field2 = 2;</code>
     * @return The bytes for field2.
     */
    com.google.protobuf.ByteString
        getField2Bytes();
  }
  /**
   * Protobuf type {@code dummy_proto}
   */
  public static final class dummy_proto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dummy_proto)
      dummy_protoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use dummy_proto.newBuilder() to construct.
    private dummy_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private dummy_proto() {
      field2_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new dummy_proto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private dummy_proto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              field1_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              field2_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cs511.proto.DummyProto.internal_static_dummy_proto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cs511.proto.DummyProto.internal_static_dummy_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cs511.proto.DummyProto.dummy_proto.class, org.cs511.proto.DummyProto.dummy_proto.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private int field1_;
    /**
     * <code>int32 field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public int getField1() {
      return field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private volatile java.lang.Object field2_;
    /**
     * <code>string field2 = 2;</code>
     * @return The field2.
     */
    @java.lang.Override
    public java.lang.String getField2() {
      java.lang.Object ref = field2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field2_ = s;
        return s;
      }
    }
    /**
     * <code>string field2 = 2;</code>
     * @return The bytes for field2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getField2Bytes() {
      java.lang.Object ref = field2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != 0) {
        output.writeInt32(1, field1_);
      }
      if (!getField2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, field2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, field1_);
      }
      if (!getField2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, field2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cs511.proto.DummyProto.dummy_proto)) {
        return super.equals(obj);
      }
      org.cs511.proto.DummyProto.dummy_proto other = (org.cs511.proto.DummyProto.dummy_proto) obj;

      if (getField1()
          != other.getField1()) return false;
      if (!getField2()
          .equals(other.getField2())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + getField1();
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cs511.proto.DummyProto.dummy_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cs511.proto.DummyProto.dummy_proto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dummy_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dummy_proto)
        org.cs511.proto.DummyProto.dummy_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cs511.proto.DummyProto.internal_static_dummy_proto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cs511.proto.DummyProto.internal_static_dummy_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cs511.proto.DummyProto.dummy_proto.class, org.cs511.proto.DummyProto.dummy_proto.Builder.class);
      }

      // Construct using org.cs511.proto.DummyProto.dummy_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field1_ = 0;

        field2_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cs511.proto.DummyProto.internal_static_dummy_proto_descriptor;
      }

      @java.lang.Override
      public org.cs511.proto.DummyProto.dummy_proto getDefaultInstanceForType() {
        return org.cs511.proto.DummyProto.dummy_proto.getDefaultInstance();
      }

      @java.lang.Override
      public org.cs511.proto.DummyProto.dummy_proto build() {
        org.cs511.proto.DummyProto.dummy_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cs511.proto.DummyProto.dummy_proto buildPartial() {
        org.cs511.proto.DummyProto.dummy_proto result = new org.cs511.proto.DummyProto.dummy_proto(this);
        result.field1_ = field1_;
        result.field2_ = field2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cs511.proto.DummyProto.dummy_proto) {
          return mergeFrom((org.cs511.proto.DummyProto.dummy_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cs511.proto.DummyProto.dummy_proto other) {
        if (other == org.cs511.proto.DummyProto.dummy_proto.getDefaultInstance()) return this;
        if (other.getField1() != 0) {
          setField1(other.getField1());
        }
        if (!other.getField2().isEmpty()) {
          field2_ = other.field2_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cs511.proto.DummyProto.dummy_proto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cs511.proto.DummyProto.dummy_proto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int field1_ ;
      /**
       * <code>int32 field1 = 1;</code>
       * @return The field1.
       */
      @java.lang.Override
      public int getField1() {
        return field1_;
      }
      /**
       * <code>int32 field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(int value) {
        
        field1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        
        field1_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object field2_ = "";
      /**
       * <code>string field2 = 2;</code>
       * @return The field2.
       */
      public java.lang.String getField2() {
        java.lang.Object ref = field2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string field2 = 2;</code>
       * @return The bytes for field2.
       */
      public com.google.protobuf.ByteString
          getField2Bytes() {
        java.lang.Object ref = field2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        field2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        
        field2_ = getDefaultInstance().getField2();
        onChanged();
        return this;
      }
      /**
       * <code>string field2 = 2;</code>
       * @param value The bytes for field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        field2_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dummy_proto)
    }

    // @@protoc_insertion_point(class_scope:dummy_proto)
    private static final org.cs511.proto.DummyProto.dummy_proto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cs511.proto.DummyProto.dummy_proto();
    }

    public static org.cs511.proto.DummyProto.dummy_proto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<dummy_proto>
        PARSER = new com.google.protobuf.AbstractParser<dummy_proto>() {
      @java.lang.Override
      public dummy_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dummy_proto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<dummy_proto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<dummy_proto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cs511.proto.DummyProto.dummy_proto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dummy_proto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dummy_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021dummy_proto.proto\"-\n\013dummy_proto\022\016\n\006fi" +
      "eld1\030\001 \001(\005\022\016\n\006field2\030\002 \001(\tB\021\n\017org.cs511." +
      "protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dummy_proto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dummy_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dummy_proto_descriptor,
        new java.lang.String[] { "Field1", "Field2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
